---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31000
  selector:
    app: flaskdemo